services:
  authsvc-build:
    build: 
      context: ./auth-svc
      target: prerelease
    image: authsvc-dev:latest
    command : ["bun", "run", "prisma-dev", "migrate", "dev"]
    environment:
      - DOTENV_PRIVATE_KEY_DEVELOPMENT
    networks: 
      - authnet
    depends_on: 
      db-authsvc:
        condition: service_healthy
  
  authsvc:
    build: 
      context: ./auth-svc
      target: prerelease
    image: authsvc-dev:latest
    environment: 
      - DOTENV_PRIVATE_KEY_DEVELOPMENT
    networks:
      - authnet
      - svcnet
    depends_on:
      authsvc-build:
        condition: service_completed_successfully
    develop:
      watch:
        - path: ./auth-svc
          action: sync+restart
          target: /auth-svc/
          ignore: 
            - ./auth-svc/node_modules
        - path: ./auth-svc/package.json
          action: rebuild

  db-authsvc:
    image: postgres:alpine
    environment: 
      - POSTGRES_PASSWORD=${AUTH_DB_PASS}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_DB=${AUTH_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 3s
    networks: 
      - authnet
    volumes: 
      - data-authsvc:/var/lib/postgresql

  userpost-build:
    build:
      context: ./post-svc
      target: prerelease
    image: userpost-dev:latest
    command : ["bun", "run", "postbuild-dev"]
    environment:
      - DOTENV_PRIVATE_KEY_DEVELOPMENT
    networks: 
      - frontnet
    depends_on:
      authsvc-build:
        condition: service_completed_successfully 
      db-userpost:
        condition: service_healthy
      
  userpost:
    build:
      context: ./post-svc
      target: prerelease
    image: userpost-dev:latest
    ports:
      - 3000:3000
    environment: 
      - DOTENV_PRIVATE_KEY_DEVELOPMENT
    networks:
      - frontnet
      - svcnet
    depends_on:
      authsvc:
        condition: service_started
      userpost-build: 
        condition: service_completed_successfully
      
    develop:
      watch:
        - path: ./post-svc
          action: sync+restart
          target: /post-svc/
          ignore: 
            - ./post-svc/node_modules
            - ./post-svc/package.json
        - path: ./post-svc/package.json
          action: rebuild

  db-userpost:
    image: postgres:alpine
    environment: 
      - POSTGRES_PASSWORD=${POST_DB_PASS}
      - POSTGRES_USER=${POST_DB_USER}
      - POSTGRES_DB=${POST_DB}
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

    networks: 
      - frontnet
    volumes: 
      - data-userpost:/var/lib/postgresql
networks: 
  frontnet:
  authnet:
  svcnet:
volumes:
  data-userpost:
  data-authsvc:
    
