services:
  authsvc-build:
    build: 
      context: ./auth-svc
    image: authsvc-prod:latest
    command : ["bun", "run", "prisma-pro", "migrate", "deploy"]
    environment:
      - DOTENV_PRIVATE_KEY_PRODUCTION
    networks: 
      - authnet
    depends_on: 
      db-authsvc:
        condition: service_healthy
  
  authsvc:
    image: authsvc-prod:latest
    environment: 
      - DOTENV_PRIVATE_KEY_PRODUCTION
    networks:
      - authnet
      - svcnet
    depends_on:
      authsvc-build:
        condition: service_completed_successfully
  
  db-authsvc:
    image: postgres:alpine
    environment: 
      - POSTGRES_PASSWORD={$AUTH_DB_PASS}
      - POSTGRES_USER={$AUTH_DB_USER}
      - POSTGRES_DB={$AUTH_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authsvc -d authsvc"]
      interval: 3s
      timeout: 3s
      retries: 3
    networks: 
      - authnet
    volumes: 
      - data-authsvc:/var/lib/postgresql

  userpost-build:
    build:
      context: ./post-svc
      
    image: userpost-prod:latest
    command : ["bun", "run", "postbuild-pro"]
    environment:
      - DOTENV_PRIVATE_KEY_PRODUCTION
    networks: 
      - frontnet
    depends_on: 
      db-userpost:
        condition: service_healthy
      

  userposts:
    image: userpost-prod:latest
    ports:
      - 3000:3000
    environment: 
      - DOTENV_PRIVATE_KEY_PRODUCTION
    networks:
      - frontnet
      - svcnet
    depends_on:
      userpost-build: 
        condition: service_completed_successfully
      authsvc:
        condition: service_started
      

  db-userpost:
    image: postgres:alpine
    environment: 
      - POSTGRES_PASSWORD={$POST_DB_PASS}
      - POSTGRES_USER={$POST_DB_USER}
      - POSTGRES_DB={$POST_DB}
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U userpost -d userpost"]
      interval: 3s
      timeout: 3s
      retries: 3
    networks: 
      - frontnet
    volumes: 
      - data-userpost:/var/lib/postgresql
networks: 
  frontnet:
  authnet:
  svcnet:
volumes:
  data-userpost:
  data-authsvc:
    
