FROM oven/bun:1.3-alpine AS base
RUN mkdir -p /usr/post-svc
WORKDIR /usr/post-svc

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock  /temp/dev
RUN cd /temp/dev && bun install --frozen-lockfile

RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod
RUN cd /temp/prod && bun install --frozen-lockfile --production

FROM base AS prerelease
RUN mkdir /post-svc
WORKDIR /post-svc
COPY --from=install /temp/dev/node_modules  node_modules
COPY . .
RUN  bun run prisma-dev generate
EXPOSE 3000
CMD [ "bun", "run", "dev" ]

FROM base AS release
WORKDIR /usr/post-svc
COPY --from=install  /temp/prod/node_modules /usr/post-svc/node_modules
COPY . .
RUN bun run build

EXPOSE 3000
CMD [ "bun", "run" , "start" ]
