-- =========================================================================
-- PRISMA TO DRIZZLE MIGRATION
-- =========================================================================
-- This file was auto-generated by introspecting the existing Prisma database.
--
-- ⚠️ IMPORTANT RUNTIME WARNING:
-- • DO NOT force execution of this raw SQL file on an existing, populated database. 
--   Doing so will trigger "Table already exists" errors and risks breaking your schema.
-- • If you must execute this raw SQL file, it should ONLY be run on a completely empty database.
--
-- 🛡️ THE SAFE APPROACH (NO DATA LOSS):
-- • To safely sync the Drizzle schema with your existing Prisma database in development 
--   or production without losing data, "do NOT run this SQL file manually". 
-- • ✔ Instead, simply run: npx drizzle-kit pull --init
/*
CREATE TABLE "Users" (
	"id" uuid PRIMARY KEY,
	"username" varchar(255) NOT NULL,
	"password_hash" varchar(2040) NOT NULL,
	"provider" varchar(255) DEFAULT 'Local' NOT NULL,
	"pid" text,
	"displayName" varchar(255),
	"fullName" varchar(255) NOT NULL,
	"firstName" varchar(255) NOT NULL,
	"lastName" varchar(255),
	"email" varchar(255) NOT NULL,
	"photoURL" varchar(2024),
	"photo" bytea,
	"photoType" varchar(255),
	"created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) with time zone NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "Users_email_key" ON "Users" ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "Users_pid_key" ON "Users" ("pid");--> statement-breakpoint
CREATE UNIQUE INDEX "Users_username_key" ON "Users" ("username");