name: run integration tests for authsvc
on:
  push
jobs: 
  test-api:
    
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: ./auth-svc
    services:
      db-authsvc:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 1s
          --health-retries 1
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build Docker Image
        run:  docker build --target prerelease -t authsvc-test:latest .
      
      - name: Run Tests in Container
        run: docker run --rm authsvc-test:latest bun run tests 
        env:
          DOTENV_PRIVATE_KEY_DEVELOPMENT: ${{ secrets.DOTENV_PRIVATE_KEY_DEVELOPMENT }}

      
      


